export default {
    DASHBOARD: 'Dashboard',
    CART: 'Cart',
    PLP: 'Product List',
    PDP: 'Product Detail',
    SPECIFICATIONS: 'Specification Detail',
    DESCRIPTIONS: 'Description Detail',
    MY_ORDERS: 'My Orders',
    EDIT_PROFILE: 'Edit Profile',
    SAVED_ADDRESS: 'Saved Address',
    E_WALLET: 'E-Wallet',
    REWARD_POINTS: 'Reward Points',
    CHANGE_PASSWORD: 'Change Password',
    NOTIFICATIONS: 'Notifications',
    MY_REVIEWS: 'My Reviews',
    ADD_ADDRESS: 'Add Address',
    ORDER_DETAIL: 'Order Detail',
    CONTACT_US: 'Contact Us',
    FORGOT_PASSWORD: 'Forgot Password',
    PRODUCT_REVIEW: 'Product Review',
    RETURN_ORDER: 'Return Order',
    CANCEL_ORDER: 'Cancel Order',
    SEARCH_SCREEN: 'Search Screen',
    CHECKOUT_SCREEN: 'Checkout Screen',
    ORDER_CONFIRMATION: 'Order Confirmation',
    ALL_REVIEWS: 'All Reviews',
    HOME: 'Home',
    CATEGORIES: 'Categories',
    PROFILE: 'Profile',
    WISHLIST:"Wishlist",
}